### ISSUE TITLE
The 'Host' HTTP header is not set when connecting to OpenStack Image Service API

### ISSUE THREAD

**Issue by ghost** [cloudfoundry/bosh-init#74]
Hi everybody,

When I use bosh-init in an OpenStack environment, I have the following error after bosh-init deploy bosh.yml

`Command 'deploy' failed:
  creating stemcell (bosh-openstack-kvm-ubuntu-trusty-go_agent 3012):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Unable to connect to the OpenStack Image Service API: Expected([200, 204, 300]) \u003c=\u003e Actual(503 Service Unavailable)\nexcon.error.response\n  :body          =\u003e \"\u003chtml\u003e\u003cbody\u003e\u003ch1\u003e503 Service Unavailable\u003c/h1\u003e\\nNo server is available to handle this request.\\n\u003c/body\u003e\u003c/html\u003e\\n\\n\"\n  :headers       =\u003e {\n    \"Cache-Control\" =\u003e \"no-cache\"\n    \"Connection\"    =\u003e \"close\"\n    \"Content-Type\"  =\u003e \"text/html\"\n  }\n  :local_address =\u003e \"192.168.1.17\"\n  :local_port    =\u003e 38884\n  :reason_phrase =\u003e \"Service Unavailable\"\n  :remote_ip     =\u003e \"10.0.0.11\"\n  :status        =\u003e 503\n  :status_line   =\u003e \"HTTP/1.0 503 Service Unavailable\\r\\n\"\n. Check task debug log for details.","ok_to_retry":false}
`

It's because I use HAProxy to get an unique endpoint for all my API (useful for SSL). HAProxy could not find a backend if no Host header is set in HTTP request. If I set the default backend to route on my Image Service API, the problem is solved. In fact, I think it's a good idea to just set the Host header in bosh-init.

This is what the HAProxy log is looking for after the bosh-init error:

`Apr 22 10:30:51 n0 haproxy[18378]: 10.0.0.119:38884 [22/Apr/2016:10:30:51.119] http-in http-in/<NOSRV> -1/-1/-1/-1/0 503 213 - - SC-- 0/0/0/0/0 0/0 "GET / HTTP/1.1"`

Thank you!

**Comment by voelzmo** [comment]
Dear @romain-pierre thanks for submitting the issue. I saw that you just closed https://github.com/cloudfoundry/bosh/issues/1237 for this one. 

The library used to connect to OpenStack is https://github.com/excon/excon which sets the `HOST` header correctly, according to our debug logs. 

My guess is that it doesn't work for you, because the `HOST` header is set to your proxy.
When you want to use a proxy between you and the OpenStack API, you can specify it in your bosh-init deployment manifest with [`properties.env`](http://bosh.io/jobs/openstack_cpi?source=github.com/cloudfoundry-incubator/bosh-openstack-cpi-release#p=env) like so
```
properties:
  env:
    http_proxy: <your proxy>
    https_proxy: <your proxy>
    no_proxy: <potential list of no_proxy domains>
```

Let me know if that works.

Just out of curiosity: If you do this for securing communication with SSL, why don't you provide certificates for your OpenStack endpoints?

As you are connecting to OpenStack, please open any follow-ups in https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release. Thanks!

**Comment by romain-pierre** [comment]
Hi,

Thank you for your answer. Ok, maybe it's an issue more with excon than bosh-init.

_I use HAProxy for many reasons, including: you can easily centralize SSL management for all your endpoint (Let's encrypt need to be updated every 3 months I think). Also, this is more comfortable if you want to make some changes to your infrastructure (if you want to migrate a service, like Keystone, from a physical machine to another one, you can switch to other backend quickly and revert if you have a problem). Obviously you can use HAProxy to distribute on different node. For user, it's more simpler because you can use 80 and 443 ports for all API and just set a different sub-domain (identity.domain.com, image.domain.com) etc._

I have omitted to say that in the Keystone service, my endpoints are correctly defined (with domain name and not only with IP address). I think your settings about http_proxy are more about client-side proxy (as mandatory) and not about entry-point proxy (as load-balancer or reverse proxy). For bosh-init (oups, for excon, so) the proxy is transparent. I will try to get the exact HTTP request to understand the problem.

**Comment by romain-pierre** [comment]
Just before, I have received this request from the same host (who run bosh-init)

`Apr 22 10:27:02 n0 haproxy[18378]: 10.0.0.119:38882 [22/Apr/2016:10:26:57.304] http-in http-in/<NOSRV> -1/-1/-1/-1/5177 400 188 - - PR-- 0/0/0/0/0 0/0 "<BADREQ>"`

Unfortunately I don't have a better trace to give... I will try to get more about this error.

**Comment by cppforlife** [comment]
@ghost any updates?

**Comment by voelzmo** [comment]
@cppforlife "@ghost" means the user deleted his/her account :) So I guess not updates here.

**Comment by fanux** [comment]
Hello, I got the same error but I can't fix it:

Command 'deploy' failed:
  creating stemcell (bosh-openstack-kvm-ubuntu-trusty-go_agent 3232.4):
    CPI 'create_stemcell' method responded with error: CmdError
```bash
{"type":"Bosh::Clouds::CloudError","message":"Unable to connect to the OpenStack Image Service API: Expected([200, 204]) \u003c=\u003e Actual(404 Not Found)\nexcon.error.response\n  :body          =\u003e \"{\\\"error\\\": {\\\"message\\\": \\\"The resource could not be found.\\\", \\\"code\\\": 404, \\\"title\\\": \\\"Not Found\\\"}}\"\n  :cookies       =\u003e [\n  ]\n  :headers       =\u003e {\n    \"Content-Length\" =\u003e \"93\"\n    \"Content-Type\"   =\u003e \"application/json\"\n    \"Date\"           =\u003e \"Thu, 23 Jun 2016 07:04:42 GMT\"\n    \"Server\"         =\u003e \"Apache/2.4.7 (Ubuntu)\"\n    \"Vary\"           =\u003e \"X-Auth-Token\"\n  }\n  :host          =\u003e \"192.168.1.121\"\n  :local_address =\u003e \"192.168.1.121\"\n  :local_port    =\u003e 35495\n  :path          =\u003e \"/identity//tokens\"\n  :port          =\u003e 80\n  :reason_phrase =\u003e \"Not Found\"\n  :remote_ip     =\u003e \"192.168.1.121\"\n  :status        =\u003e 404\n  :status_line   =\u003e \"HTTP/1.1 404 Not Found\\r\\n\"\n. Check task debug log for details.","ok_to_retry":false}
```

I connect to my image service on port 9292 , got those messages 
```bash
{"versions": [{"status": "CURRENT", "id": "v2.3", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.2", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.1", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v2.0", "links": [{"href": "http://192.168.1.121:9292/v2/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.1", "links": [{"href": "http://192.168.1.121:9292/v1/", "rel": "self"}]}, {"status": "SUPPORTED", "id": "v1.0", "links": [{"href": "http://192.168.1.121:9292/v1/", "rel": "self"}]}]}
```

**Comment by fanux** [comment]
I solved the error.
I use the identity v3 lead to this error.
just change the `auth_url`

http://domain/identity    =>   http://domain/identity/v2.0/
